# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e02f077e0bef894f789beeb2ebf7eebd11a5847668a87b0dfc33594207a73cc65f17607f383774d22967aec415f6eea8011a260bc8ee2726f12100dc5230051e

test:
  secret_key_base: 8338fa7de0c40882b38bece140d8d7f6ec7216a297824c833c9f9196d922734aeb6b68a9d8557920771f2df31f296b30bf807eb880f82def76fb606d04be8d94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
